name = "roman-os"
type = "javascript"
compatibility_date = "2024-09-26"

[[d1_databases]]
binding = "DB"
database_name = "roman-os-db"
database_id = "8812cc48-2159-4b47-867e-7830a107a288"

[vars]
GOOGLE_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbxCJVTtQF8YyGYFsT89hG2mEJHV1KR-3rQY/exec"

[build]
command = ""
